spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:postgresql://host.docker.internal:1856/mealpick
    username: ${PG_USER}
    password: ${PG_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

server:
  port: 8080

